version: "3.8"

services:
  db:
    image: postgres:16
    container_name: ellpPostgres
    restart: always
    environment:
      POSTGRES_USER: user123
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: ellpDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  dbTest:
    image: postgres:16
    container_name: ellpPostgresTest
    restart: "no"
    environment:
      POSTGRES_USER: user123
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: ellpDbTest
    ports:
      - "5433:5432"

volumes:
  postgres_data:
